#!/usr/bin/env python3
"""Install genuine pinned Prek hooks with documented canonical execution.

Install the owning pinned upstream checker implementations faithfully.
The helper transforms the real generated Prek pre-commit and pre-push scripts,
keeping their actual checkers, executables and arguments intact, then reconciles managed
Repro hooks. All integration controls use real tools/filesystem; no mocks.
"""
from __future__ import annotations
import argparse
import hashlib
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile

from repro_hook_factory import SelectedFactory
from held_hook_boundary import HeldHookBoundary

BOUNDARY = None

CONTRACT = "reprobuild.managed-hook.v1.pre-commit.434c2eeac4079591"
EXPORT = b"export PREK_NO_FAST_PATH=1\n"
GENERATED = b"# File generated by prek: https://github.com/j178/prek\n"

def run(argv: list[str], cwd: Path) -> str:
    return subprocess.check_output(argv, cwd=cwd, text=True, stderr=subprocess.STDOUT).strip()

def native_install_environment(env: dict[str, str], git: str, root: Path, hooks: Path) -> dict[str, str]:
    # Native Prek refuses a nonempty hooksPath, then installs in common/hooks.
    # Override only this child command after proving that same owned destination.
    if any(key == "GIT_CONFIG_COUNT" or key == "GIT_CONFIG_PARAMETERS"
            or key.startswith(("GIT_CONFIG_KEY_", "GIT_CONFIG_VALUE_")) for key in env):
        raise RuntimeError("ambiguous inherited Git command configuration")
    common = Path(run([git, "rev-parse", "--path-format=absolute", "--git-common-dir"], root))
    default_hooks = common / "hooks"
    if default_hooks.is_symlink() or default_hooks.resolve() != hooks:
        raise RuntimeError("native default hooks differ from verified owning hooks")
    # main already validates effective ownership, including its narrowly
    # qualified registered-worktree relative-path repair before installation.
    child = env.copy()
    child["GIT_CONFIG_COUNT"] = "1"
    child["GIT_CONFIG_KEY_0"] = "core.hooksPath"
    child["GIT_CONFIG_VALUE_0"] = ""
    return child

def native_install_to_terminal(argv: list[str], root: Path, env: dict[str, str]) -> None:
    child = subprocess.Popen(argv, cwd=root, env=env)
    interruption = None
    while True:
        try:
            code = child.wait()
            break
        except (KeyboardInterrupt, InterruptedError) as error:
            if interruption is None:
                interruption = error
    if interruption is not None:
        raise interruption
    if code:
        raise subprocess.CalledProcessError(code, argv)

def selected_tool(name: str) -> str:
    found = shutil.which(name)
    if not found:
        raise RuntimeError(f"missing declared native tool: {name}")
    return str(Path(found).absolute())

# Entire genuine pinned native template, including whitespace and final newlines.
# Only its independently selected owning executable binding varies by native SDK.
NATIVE_TEMPLATE = b'#!/bin/sh\n# File generated by prek: https://github.com/j178/prek\n# ID: 182c10f181da4464a3eec51b83331688\n\nHERE="$(cd "$(dirname "$0")" && pwd)"\nPREK="@OWNING_PREK_EXECUTABLE@"\n\n# Check if the full path to prek is executable, otherwise fallback to PATH\nif [ ! -x "$PREK" ]; then\n    PREK="prek"\nfi\n\nexec "$PREK" hook-impl --hook-dir "$HERE" --script-version 4 --hook-type=pre-commit -- "$@"\n\n'

def native_generated_body(prek: str, hook_type: str = "pre-commit") -> bytes:
    if hook_type not in ("pre-commit", "pre-push"):
        raise RuntimeError("unqualified native hook type")
    return NATIVE_TEMPLATE.replace(b"@OWNING_PREK_EXECUTABLE@", os.fsencode(prek)).replace(
        b"--hook-type=pre-commit", os.fsencode("--hook-type=" + hook_type))

def canonical_body(prek: str, hook_type: str = "pre-commit") -> bytes:
    native = native_generated_body(prek, hook_type)
    first, rest = native.split(b"\n", 1)
    return first + b"\n" + EXPORT + rest

def canonical_generated_body(body: bytes, prek: str, mode: int, hook_type: str = "pre-commit") -> bytes:
    if mode != 0o755 or body != native_generated_body(prek, hook_type):
        raise RuntimeError("unexpected exact owning native Prek hook body or mode")
    return canonical_body(prek, hook_type)

def validate_prior_owned_body(body: bytes, mode: int, prek: str) -> None:
    if mode != 0o755:
        raise RuntimeError("former owning local hook mode changed")
    if body not in (native_generated_body(prek), canonical_body(prek)):
        raise RuntimeError("unknown or modified owning local hook body")

KNOWN_MANAGED_BODIES = {'post-checkout': '559e7ef6b042c686c97eaa0e39fb388224376d8b3c7f8d2b8014f2b72db5592c', 'post-checkout.repro-managed': '9f2984dd9a84a7c0e8fe35e27e85b3d1119439d30941641d2c52e0180fa9a67d', 'post-commit': 'd32025c9c8d3d940f0b8a4628365abd9a6f473c6285074ae75095a9d70e2d98b', 'post-commit.repro-managed': '7547f2c80dc2ede98ed08c6458995aca9ae36ada500f09af034b9fc0cda9224b', 'post-merge': 'bfbe09e064471797f5927251a76c81a4d647edc876bdc6186118b5f810ec13fd', 'post-merge.repro-managed': 'd5ef6453ef70840bbb0d2c333ccc429447d7a089701623c6db8c41e7da08f65e', 'pre-commit': '06cfcb59c42b99e9432c469f6bce7dc4fa5b0fa7c6f4f4e0548a1161233cf576', 'pre-commit.repro-managed': '598ed91d257d1d236de042e708bd239837e069b2ee6fd583cf6b2d121f294507', 'pre-push': 'f5084841c5edfe6bfdaba3ad55c142b87e4e93b725754de0af553b57709e5c29', 'pre-push.repro-managed': '642c37aca860a03ee6e7c2d0f941bf6fbdd1202c9f356c4fe68bf3ad3bfe6da6'}


# Existing Linux-author bodies remain explicit qualified legacy preimages.
LEGACY_MANAGED_BODIES = KNOWN_MANAGED_BODIES.copy()

def qualified_managed_prior(name: str, digest: str) -> bool:
    return digest == KNOWN_MANAGED_BODIES.get(name) or digest == LEGACY_MANAGED_BODIES.get(name)


# Exact existing owning checkout sample and owning Git2.53 native template.
# Git never dispatches this exact .sample filename; all bytes/modes are preserved.
KNOWN_GIT_PRE_PUSH_SAMPLE_BODIES = {
    "f35ff977f07f76b61e0ebc047bf500793d22d95fbcf86c6ab95561b6ba339bc8",
    "212424610fb7562dfc6274e127946f529de19bf0c73744860be2c55247925668",
}


KNOWN_GIT_SAMPLES = {'applypatch-msg.sample': ['37ca5da86ab699db4572609ab0fb2d2d072dd254f4d3b5d56c21193ba44eccce', 'eff2c3264abcf88b09cbcd9fdf9e3770c01d2c0932b698f3f2bd5fc50bb8812f'], 'commit-msg.sample': ['2c1bb732a515631875c2b4bb54311077e8028c4efca3ebe596133932fa520340', '3a75e6e4575b274a47d898b2e63de06fceecd125e510231eb1bd84110fd081b1'], 'fsmonitor-watchman.sample': ['3ee619bc7217025d5a9c92785c3e9fd313bedaeb981c4f79f1f1fb802b80fdbf', '6512786c6b67dc73acfb070cc7597c2d09940afaaddcc2ea45b7d39e6f510ab7'], 'post-update.sample': ['f02167601f61d3a7f2725e94c790cf0f56c729bd63d96e0cbbcadca05a33502b', 'f8192e86efc5a8130e7f5cbdd9122872a29880da5cfff51378478080622da332'], 'pre-applypatch.sample': ['cd92ca930f95859f23a676b64bd8e0159519efba814b40f8be01bb523b858494', 'dab0584577cc1f1425637051b252911787dda69ebe77bb5baa09cf5c6eefa5eb'], 'pre-commit.sample': ['338daa45efd853599a97e0c84d0feb5863797ccb8b85572e92d10d8461269ab6', '8648b08f9877b0099aec8d90b92df1b9a292c067744a8964ceb747668e9fbc90'], 'pre-merge-commit.sample': ['474c16b6e8b61c7f590fdb67374b8ceb37b58025897b7e9469a6420f183715d1', '52ce5ef56a85753cb2891c2f1274cd14a287e8ba6e47f1cd4f0e67991238e662'], 'pre-push.sample': ['212424610fb7562dfc6274e127946f529de19bf0c73744860be2c55247925668', 'f35ff977f07f76b61e0ebc047bf500793d22d95fbcf86c6ab95561b6ba339bc8'], 'pre-rebase.sample': ['285f0a7d7d24b6afab04d3bed7513d109604bb4702c995ea23e9018f5c9c5bcf', '48aa7f470363e8ac81bc7707f7b935044f17e37c430a64008ef9ca6760035eb3'], 'pre-receive.sample': ['1289c1d78d0ad7630cf7ea9f19e8e9f991a8d1565116beaf38e169ae946c099f', 'a6a6547077617556bd6a5729575ec0f003c80cac264439968c459c74d00b0020'], 'prepare-commit-msg.sample': ['1704a1edd6fae6c84dda7bbe1b5b1d0f61a860439d7b58e2659f61b7ba6f3418', '880a38d177f8143b5c062ca476ef34f4967c58121251e4648a3e9ec9629f6803'], 'push-to-checkout.sample': ['0ac671c7451352f26be3caabab354fad20bdcc2d2bf7edf026fd0655176a8728', '87760462f0a17b21b294e5a8a34e8d64699af0bd41c91940e2fa6b5251757348'], 'sendemail-validate.sample': ['3e63147e70eee60bb9cf57adafb5ba219cc9e6609ee334d294729658e9b14822', 'a6b824290d15ffe0dbdb4cc856d86ac541ae300cb86b7b183df6a6ca2d35065c'], 'update.sample': ['8b72d6efcbeb4cf670120f40a940ef06b716e8befe4801ede61042bb18738156', 'd8e942bf3c04c29bf6b5ec3f72cc7ea640dcf600e0e8bed97cb71be5500c43e3']}

def complete_hook_inventory(hooks: Path, prek: str) -> dict[str, tuple[bytes, int]]:
    result = {}
    if not hooks.exists():
        return result
    for path in hooks.iterdir():
        info = path.lstat()
        if stat.S_ISLNK(info.st_mode):
            raise RuntimeError(f"unowned hook entry symlink: {path.name}")
        if not stat.S_ISREG(info.st_mode):
            raise RuntimeError(f"unowned hook entry type: {path.name}")
        body = path.read_bytes()
        mode = stat.S_IMODE(info.st_mode)
        digest = hashlib.sha256(body).hexdigest()
        expected = KNOWN_MANAGED_BODIES.get(path.name)
        allowed = qualified_managed_prior(path.name, digest)
        if path.name == "pre-commit":
            allowed = allowed or body in (native_generated_body(prek), canonical_body(prek))
        if path.name in KNOWN_GIT_SAMPLES:
            allowed = digest in KNOWN_GIT_SAMPLES[path.name]
        if path.name in ("pre-commit.repro-local", "pre-push.repro-local"):
            hook_type = path.name.removesuffix(".repro-local")
            allowed = body in (native_generated_body(prek, hook_type), canonical_body(prek, hook_type))
        for prefix, hook_type in (("pre-commit.repro-local.backup-", "pre-commit"),
                                    ("retired-owned-pre-push-local-", "pre-push")):
            if path.name.startswith(prefix):
                allowed = path.name == prefix + digest and body in (native_generated_body(prek, hook_type), canonical_body(prek, hook_type))
        if not allowed or mode != 0o755:
            raise RuntimeError(f"unknown or modified hook entry body or mode: {path.name}")
        result[path.name] = (body, mode)
    return result


def pre_push_inventory(hooks: Path, prek: str) -> dict[str, tuple[bytes, int]]:
    inventory = {}
    if not hooks.exists():
        return inventory
    for path in hooks.iterdir():
        if not path.name.startswith("pre-push"):
            continue
        expected = KNOWN_MANAGED_BODIES.get(path.name)
        if path.name == "pre-push.repro-local":
            expected = "native-or-canonical-owning-prek-body"
        sample = path.name == "pre-push.sample"
        if expected is None and not sample:
            raise RuntimeError(f"unknown pre-push hook entry: {path.name}")
        metadata = path.lstat()
        if not stat.S_ISREG(metadata.st_mode):
            raise RuntimeError(f"unowned pre-push hook type: {path.name}")
        body = path.read_bytes()
        mode = stat.S_IMODE(metadata.st_mode)
        digest = hashlib.sha256(body).hexdigest()
        qualified_body = digest in KNOWN_GIT_PRE_PUSH_SAMPLE_BODIES if sample else qualified_managed_prior(path.name, digest)
        if path.name == "pre-push.repro-local":
            qualified_body = qualified_body or body in (native_generated_body(prek, "pre-push"), canonical_body(prek, "pre-push"))
        if mode != 0o755 or not qualified_body:
            raise RuntimeError(f"modified pre-push hook body or mode: {path.name}")
        inventory[path.name] = (body, mode)
    return inventory

OWNING_DECLARATIONS = (
    ".pre-commit-config.yaml", ".editorconfig", "flake.nix", "flake.lock",
    "tools/install-canonical-hooks.py", "tools/repro_hook_factory.py", "tools/held_hook_boundary.py",
)

def owned_common_directory(git: str, root: Path) -> Path:
    # Git registration and primary-owned metadata establish shared-hook ownership.
    raw_common = Path(run([git, "rev-parse", "--git-common-dir"], root))
    lexical_common = raw_common if raw_common.is_absolute() else root / raw_common
    if lexical_common.is_symlink():
        raise RuntimeError("symlink Git common directory")
    common = lexical_common.resolve(strict=True)
    records = subprocess.check_output(
        [git, "worktree", "list", "--porcelain", "-z"], cwd=root
    ).split(b"\0\0")
    registered = []
    for record in records:
        fields = record.split(b"\0")
        if fields and fields[0].startswith(b"worktree "):
            registered.append(Path(os.fsdecode(fields[0][9:])))
    if not registered or not any(path.resolve() == root for path in registered):
        raise RuntimeError("owning worktree is not registered")
    primary = registered[0]
    if primary.is_symlink() or not primary.is_dir():
        raise RuntimeError("primary worktree is not an owned regular directory")
    primary = primary.resolve(strict=True)
    primary_git = primary / ".git"
    if primary_git.is_symlink() or not primary_git.is_dir() or primary_git.resolve() != common:
        raise RuntimeError("Git common directory does not belong to registered primary")
    git_dir = Path(run([git, "rev-parse", "--absolute-git-dir"], root))
    if git_dir.is_symlink() or not git_dir.is_dir():
        raise RuntimeError("owning Git metadata is not a regular directory")
    resolved_git_dir = git_dir.resolve(strict=True)
    if root == primary:
        if resolved_git_dir != common:
            raise RuntimeError("primary Git metadata differs from common directory")
    else:
        if resolved_git_dir.parent != common / "worktrees":
            raise RuntimeError("linked worktree metadata is outside owning common directory")
        marker = root / ".git"
        if marker.is_symlink() or not marker.is_file():
            raise RuntimeError("linked worktree registration is not a regular file")
        registration = resolved_git_dir / "gitdir"
        if registration.is_symlink() or not registration.is_file():
            raise RuntimeError("missing genuine linked-worktree registration")
        if Path(registration.read_text().strip()).resolve(strict=True) != marker.resolve(strict=True):
            raise RuntimeError("linked-worktree registration points elsewhere")
    for name in OWNING_DECLARATIONS:
        current, original = root / name, primary / name
        for path in (current, original):
            if path.is_symlink() or not path.is_file():
                raise RuntimeError(f"owning declaration is not regular: {name}")
        if current.read_bytes() != original.read_bytes():
            raise RuntimeError(f"primary/current owning declaration differs: {name}")
    return common

def atomic_write(path: Path, data: bytes, mode: int) -> None:
    if BOUNDARY is None:
        raise RuntimeError("missing admitted hook mutation boundary")
    BOUNDARY.guard()
    expected = BOUNDARY.bodies(BOUNDARY.entries)
    expected[path.name] = (data, mode)
    descriptor, filename = tempfile.mkstemp(prefix=".canonical-prek-", dir=path.parent)
    temporary = Path(filename)
    held_temporary = os.dup(descriptor)
    original_temporary = os.fstat(descriptor)
    temporary_identity = (original_temporary.st_dev, original_temporary.st_ino)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        BOUNDARY.guard(ignored_temporary=temporary)
        current_temporary = temporary.lstat()
        if (current_temporary.st_dev, current_temporary.st_ino) != temporary_identity:
            raise RuntimeError("owned temporary hook identity changed before commit")
        if BOUNDARY.row(held_temporary) != (*temporary_identity, mode, 1, data):
            raise RuntimeError("owned temporary hook bytes/mode/linkcount changed before commit")
        os.replace(temporary, path)
        BOUNDARY.accept(expected, {path.name})
    finally:
        os.close(held_temporary)
        if temporary.exists() or temporary.is_symlink():
            current_temporary = temporary.lstat()
            if not stat.S_ISREG(current_temporary.st_mode) or (current_temporary.st_dev, current_temporary.st_ino) != temporary_identity:
                raise RuntimeError("unknown temporary replacement retained after failed hook commit")
            temporary.unlink()

def guarded_ensure(repro, root, env, factory):
    BOUNDARY.guard()
    expected = BOUNDARY.bodies(BOUNDARY.entries)
    expected.update({name: (body, 0o755) for name, body in factory.bodies.items()})
    subprocess.run([str(repro), "hooks", "ensure", "--vcs", "."], cwd=root, env=env, check=True)
    BOUNDARY.accept(expected, set(factory.bodies))


def install_main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repro", required=True, help="explicit measured matching managed-hook engine")
    parser.add_argument("--bootstrap-managed", action="store_true",
                        help="ownership-check and establish matching managed hooks before canonical installation")
    args = parser.parse_args()
    root = Path.cwd().resolve()
    git = selected_tool("git")
    prek = selected_tool("prek")
    repro = Path(args.repro).absolute()
    if not repro.is_file() or not os.access(repro, os.X_OK):
        raise RuntimeError("missing selected matching Repro executable")
    if Path(run([git, "rev-parse", "--show-toplevel"], root)).resolve() != root:
        raise RuntimeError("run from actual owning repository root")
    if not (root / ".pre-commit-config.yaml").is_file():
        raise RuntimeError("missing owning portable standard config")
    if run([prek, "--version"], root) != "prek 0.3.6":
        raise RuntimeError("unqualified native Prek version")
    global KNOWN_MANAGED_BODIES, CONTRACT
    factory = SelectedFactory(repro, Path(git), root)
    KNOWN_MANAGED_BODIES = factory.hashes
    CONTRACT = factory.contract
    if run([str(repro), "hooks", "protocol", "--require=2", "--hook-contract=" + CONTRACT], root) != "2":
        raise RuntimeError("matching managed hook protocol failed")
    common = owned_common_directory(git, root)
    hooks = common / "hooks"
    if hooks.is_symlink() or (hooks.exists() and not hooks.is_dir()):
        raise RuntimeError("own hooks directory is symlink or non-directory")
    configured = subprocess.run([git, "config", "--get", "core.hooksPath"], cwd=root, text=True, capture_output=True)
    if configured.returncode not in (0, 1):
        raise RuntimeError("cannot inspect own hook path")
    repair_registered_relative_path = False
    if configured.returncode == 0:
        raw = Path(configured.stdout.strip())
        scope = run([git, "config", "--show-scope", "--get", "core.hooksPath"], root).split()[0]
        repair_registered_relative_path = (
            str(raw) == ".git/hooks" and scope == "local" and not (root / ".git").is_dir()
        )
        resolved = (root / raw).resolve() if not raw.is_absolute() else raw.resolve()
        if resolved != hooks and not repair_registered_relative_path:
            raise RuntimeError("nonowning or unqualified hooks directory")
    actual_hooks = Path(run([git, "rev-parse", "--path-format=absolute", "--git-path", "hooks"], root))
    if actual_hooks.is_symlink() or (
        actual_hooks.resolve() != hooks.resolve() and not repair_registered_relative_path
    ):
        raise RuntimeError("effective Git hooks path is not the owning directory")
    if actual_hooks.exists() and not actual_hooks.is_dir():
        raise RuntimeError("effective hooks path is non-directory")
    for name, expected_hash in KNOWN_MANAGED_BODIES.items():
        path = hooks / name
        if path.is_symlink():
            raise RuntimeError(f"unowned managed hook symlink: {name}")
        if path.exists():
            if not path.is_file():
                raise RuntimeError(f"unowned managed hook type: {name}")
            body = path.read_bytes()
            if name == "pre-commit" and not body.startswith(b"#!/usr/bin/env sh\n# reprobuild hook dispatcher protocol=2\n"):
                validate_prior_owned_body(body, stat.S_IMODE(path.stat().st_mode), prek)
            elif not qualified_managed_prior(name, hashlib.sha256(body).hexdigest()) or stat.S_IMODE(path.stat().st_mode) != 0o755:
                raise RuntimeError(f"unknown or modified managed hook template: {name}")
    original_pre_push = pre_push_inventory(hooks, prek)
    complete_before = complete_hook_inventory(hooks, prek)

    env = os.environ.copy()
    env["PREK_NO_FAST_PATH"] = "1"
    env["REPROBUILD_REPRO"] = str(repro)
    # The owning config requires language_version system; Prek refuses
    # managed Python downloads. The locked SDK supplies native Python on PATH.
    existing = hooks / "pre-commit"
    if existing.is_symlink():
        raise RuntimeError("unowned existing pre-commit symlink")
    if existing.exists():
        if existing.is_symlink() or not existing.is_file():
            raise RuntimeError("unowned existing pre-commit hook shape")
        previous = existing.read_bytes()
        if not previous.startswith(b"#!/usr/bin/env sh\n# reprobuild hook dispatcher protocol=2\n"):
            validate_prior_owned_body(previous, stat.S_IMODE(existing.stat().st_mode), prek)
    preserved = hooks / "pre-commit.repro-local"
    preserved_before = None
    if preserved.is_symlink():
        raise RuntimeError("unowned preserved local hook symlink")
    if preserved.exists():
        if preserved.is_symlink() or not preserved.is_file():
            raise RuntimeError("unowned preserved local hook shape")
        preserved_before = preserved.read_bytes()
        validate_prior_owned_body(preserved_before, stat.S_IMODE(preserved.stat().st_mode), prek)
    backup = None
    if preserved_before is not None and preserved_before != canonical_body(prek):
        backup = hooks / ("pre-commit.repro-local.backup-" + hashlib.sha256(preserved_before).hexdigest())
        if backup.is_symlink() or (backup.exists() and (
            not backup.is_file() or backup.read_bytes() != preserved_before
            or stat.S_IMODE(backup.stat().st_mode) != stat.S_IMODE(preserved.stat().st_mode)
        )):
            raise RuntimeError("unowned preserved-template backup")
    if not args.bootstrap_managed and set(original_pre_push) - {"pre-push.sample", "pre-push.repro-local"} != {"pre-push", "pre-push.repro-managed"}:
        raise RuntimeError("matching managed hooks must be established by ownership-checked caller bootstrap")
    push_before = original_pre_push.get("pre-push.repro-local")
    push_backup = None
    if push_before is not None and push_before[0] != canonical_body(prek, "pre-push"):
        push_backup = hooks / ("retired-owned-pre-push-local-" + hashlib.sha256(push_before[0]).hexdigest())
        if push_backup.is_symlink() or (push_backup.exists() and (
            not push_backup.is_file() or push_backup.read_bytes() != push_before[0]
            or stat.S_IMODE(push_backup.stat().st_mode) != push_before[1]
        )):
            raise RuntimeError("unowned former pre-push local backup")
    protected_before = {name: value for name, value in complete_before.items()
                        if name not in KNOWN_MANAGED_BODIES and name not in ("pre-commit.repro-local", "pre-push.repro-local")}
    install_env = native_install_environment(env, git, root, hooks)
    # All ownership/refusal checks precede the first directory or hook write.
    factory.guard()
    global BOUNDARY
    BOUNDARY = HeldHookBoundary(root, common, hooks, git, factory, complete_before)
    BOUNDARY.guard()
    had_hooks = hooks.exists()
    hooks.mkdir(exist_ok=True)
    if not had_hooks:
        BOUNDARY.accept_created_directory()
    else:
        BOUNDARY.guard()
    if repair_registered_relative_path:
        # Repair only the verified primary-owned local legacy setting after all checks.
        BOUNDARY.guard()
        old_local = BOUNDARY.git_read("config", "--local", "--null", "--list")
        subprocess.run([git, "config", "--local", "core.hooksPath", str(hooks)], cwd=root, check=True)
        BOUNDARY.accept_config_repair(old_local)
        effective = Path(run([git, "rev-parse", "--path-format=absolute", "--git-path", "hooks"], root))
        if effective.is_symlink() or effective.resolve() != hooks:
            raise RuntimeError("registered worktree hook path repair did not select owning common hooks")
    if args.bootstrap_managed:
        # Separate caller bootstrap: every ownership check above completed before
        # matching ensure creates any hook. Preserve existing pre-push entries.
        guarded_ensure(repro, root, env, factory)
        current_pre_push = pre_push_inventory(hooks, prek)
        expected_names = {"pre-push", "pre-push.repro-managed"} | (set(original_pre_push) & {"pre-push.sample", "pre-push.repro-local"})
        if set(current_pre_push) != expected_names:
            raise RuntimeError("matching bootstrap did not create qualified pre-push hooks")
        for name, snapshot in original_pre_push.items():
            if name in KNOWN_MANAGED_BODIES:
                current = current_pre_push.get(name)
                if current != (factory.bodies[name], 0o755):
                    raise RuntimeError(f"bootstrap did not produce exact selected factory role: {name}")
            elif current_pre_push.get(name) != snapshot:
                raise RuntimeError(f"bootstrap changed existing pre-push body or mode: {name}")
        for name, expected_hash in KNOWN_MANAGED_BODIES.items():
            target = hooks / name
            if target.is_symlink() or not target.is_file() or stat.S_IMODE(target.stat().st_mode) != 0o755:
                raise RuntimeError(f"bootstrap produced unowned managed hook shape: {name}")
            if hashlib.sha256(target.read_bytes()).hexdigest() != expected_hash:
                raise RuntimeError(f"bootstrap produced unexpected managed hook body: {name}")
        local = hooks / "pre-commit.repro-local"
        if local.is_symlink() or (local.exists() and not local.is_file()):
            raise RuntimeError("bootstrap produced unowned preserved local hook shape")
        if local.exists():
            local_body = local.read_bytes()
            validate_prior_owned_body(local_body, stat.S_IMODE(local.stat().st_mode), prek)
            if preserved_before is not None and local_body != preserved_before:
                raise RuntimeError("bootstrap changed preserved local hook body")
        elif preserved_before is not None:
            raise RuntimeError("bootstrap removed preserved local hook")
        complete_after = complete_hook_inventory(hooks, prek)
        for name, value in protected_before.items():
            if complete_after.get(name) != value:
                raise RuntimeError(f"bootstrap changed protected hook entry: {name}")
        factory.guard()
        print("Ownership-checked matching managed bootstrap complete")
        return
    persisted_config = subprocess.check_output([git, "config", "--null", "--show-origin", "--list"], cwd=root)
    # Snapshot only the finite validated slots this migration owns.
    slots = ("pre-commit", "pre-commit.repro-local", "pre-push", "pre-push.repro-local")
    snapshots = {}
    for name in slots:
        path = hooks / name
        snapshots[name] = (path.read_bytes(), stat.S_IMODE(path.stat().st_mode)) if path.exists() else None
    success = False
    canonical = canonical_body(prek)
    canonical_push = canonical_body(prek, "pre-push")
    try:
        if backup is not None and not backup.exists():
            atomic_write(backup, preserved_before, 0o755)
        if push_backup is not None and not push_backup.exists():
            atomic_write(push_backup, push_before[0], push_before[1])
        # The genuine installer recognizes these exact qualified native bodies.
        # It therefore constructs both scripts without renaming managed dispatchers
        # to extra legacy hooks and without its overwrite option.
        for hook_type in ("pre-commit", "pre-push"):
            atomic_write(hooks / hook_type, native_generated_body(prek, hook_type), 0o755)
        BOUNDARY.guard()
        expected_native = BOUNDARY.bodies(BOUNDARY.entries)
        native_install_to_terminal([prek, "install", "--prepare-hooks", "--hook-type", "pre-commit",
                                    "--hook-type", "pre-push"], root, install_env)
        BOUNDARY.accept(expected_native, {"pre-commit", "pre-push"})
        for hook_type in ("pre-commit", "pre-push"):
            generated = hooks / hook_type
            if generated.is_symlink() or not generated.is_file():
                raise RuntimeError("actual generated hook is not owned regular file")
            body = canonical_generated_body(generated.read_bytes(), prek,
                                            stat.S_IMODE(generated.stat().st_mode), hook_type)
            local = hooks / (hook_type + ".repro-local")
            previous = snapshots[hook_type + ".repro-local"]
            if local.is_symlink() or (local.exists() and not local.is_file()):
                raise RuntimeError("preserved local hook changed shape during installation")
            observed = (local.read_bytes(), stat.S_IMODE(local.stat().st_mode)) if local.exists() else None
            if observed != previous:
                raise RuntimeError("preserved local hook changed during installation")
            atomic_write(generated, body, 0o755)
            atomic_write(local, body, 0o755)
        guarded_ensure(repro, root, env, factory)
        expected_push = dict(original_pre_push)
        expected_push["pre-push.repro-local"] = (canonical_push, 0o755)
        if pre_push_inventory(hooks, prek) != expected_push:
            raise RuntimeError("unexpected pre-push migration inventory")
        for name, digest in KNOWN_MANAGED_BODIES.items():
            target = hooks / name
            if target.is_symlink() or not target.is_file() or stat.S_IMODE(target.stat().st_mode) != 0o755 or hashlib.sha256(target.read_bytes()).hexdigest() != digest:
                raise RuntimeError("migration changed qualified managed hook: " + name)
        success = True
    finally:
        if not success:
            # Do not overwrite or delete any unknown concurrent replacement.
            # Failed external installation retains its explicit partial state.
            print("Failed native migration retained: inspect exact partial hook state; no automatic rollback", file=sys.stderr)
        if subprocess.check_output([git, "config", "--null", "--show-origin", "--list"], cwd=root) != persisted_config:
            raise RuntimeError("persisted Git configuration changed during native installation")
        for old_backup, expected in ((backup, None if preserved_before is None else (preserved_before, 0o755)),
                                    (push_backup, push_before)):
            if old_backup is not None and (
                old_backup.is_symlink() or not old_backup.is_file()
                or (old_backup.read_bytes(), stat.S_IMODE(old_backup.stat().st_mode)) != expected
            ):
                raise RuntimeError("qualified former hook backup changed")
    for hook_type, expected in (("pre-commit", canonical), ("pre-push", canonical_push)):
        local = hooks / (hook_type + ".repro-local")
        if local.is_symlink() or not local.is_file() or stat.S_IMODE(local.stat().st_mode) != 0o755 or local.read_bytes() != expected:
            raise RuntimeError("reconciled local hook did not preserve canonical native script")
    complete_after = complete_hook_inventory(hooks, prek)
    for name, value in protected_before.items():
        if complete_after.get(name) != value:
            raise RuntimeError(f"installation changed protected hook entry: {name}")
    BOUNDARY.guard()
    print("Canonical pinned commit and push hooks installed with preserved managed dispatchers")

def main() -> None:
    try:
        install_main()
    finally:
        if BOUNDARY is not None:
            BOUNDARY.close()

if __name__ == "__main__":
    main()
